### ISSUE TITLE
Arachnotron eyes lightmap slightly misaligned

### ISSUE THREAD

**Issue by mgtroyas** [NightFright2k19/gzdoom_brightmaps#2]
Arachnotron eyes lightmap is slightly misaligned to the left, is barely visible on this screenshot, most noticeable on dark rooms.
![arachnotron](https://user-images.githubusercontent.com/30797135/127335019-c36fc829-d94c-4620-9a67-f338598b443b.png)

**Comment by NightFright2k19** [comment]
Are you using the spritefix or vanilla version? What happens if you use the other one?

**Comment by mgtroyas** [comment]
I'm using the spritefix version. If I load the vanilla one, the brightmap is aligned.

**Comment by NightFright2k19** [comment]
Are you actually also loading the spritefixes before applying these brightmaps, then? What I see here is spritefix brightmap being applied to a vanilla sprite. 

You seem to be using a PWAD. Which one is it? If it has custom Arachnotron sprites inside (e.g. because of palette adjustments), spritefixes are useless since they are overwritten by the PWAD version again. In that case, you would have to use vanilla brightmaps.

**Comment by mgtroyas** [comment]
Mmm... I was accidentally loading the spritefixes _after_ the brightmaps. But I've changed the load order (it appears so on the GZDoom log) and on a regular Doom 2 game the order doesn't make any difference, it works indeed.

Anyway, I've researched the problem a bit more and I think I found the cause: I didn't mention I was playing Sunlust.wad. I didn't thought it to be relevant as I assumed it didn't contain enemies modifications... but I extracted it with the WadExt tool and found a SPRITES folder with all the original images on it, including the Arachnotron. So Sunlust.wad is replacing the fixed sprites with the original ones, that's why it needs the original lightmaps.

I'm no expert editing wads but I assumed the user created wads shouldn't contain that folder as it's already provided by Doom2.wad and also it's copyrighted material... I extracted other user created wads like Syringe.wad and in fact it doesn't contain the SPRITES folder...

**Comment by NightFright2k19** [comment]
Some PWADs come with their own palette. In order for the regular Doom sprites to look correct still, all of them must be converted to the new palette and included with the wad. Usually, vanilla sprites are used as a base for this, which will undo the spritefixes since they will be loaded before. Loading them after would ruin the palette. 

You have two choices in such cases:
1) You are lucky and someone made spritefixes for those PWADs. In fact, some do exist, made by the spritefix author, e.g. Ancient Aliens. Sunlust might also be available. Then you load the PWAD, those special spritefixes, then the spritefix brightmaps. Kinda complicated.
2) Load vanilla brightmaps instead. That's one of the reasons I separated them from the spritefix versions, anyway.

One way or the other... this isn't a problem with this mod, so I am closing here now.
